import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Torus Redis Instance",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h2 className="text-center font-bold pt-2 text-gray-400">Redis Custom DB Instance</h2>
        {children}
        </body>
    </html>
  );
}
